/**
 * Favicon Package - Generated by RJL.io
 * https://rjl.io/favicon-generator/
 * Copyright 2026 RJL.io - All Rights Reserved
 */

import React, { useEffect } from 'react';

export const FaviconMeta: React.FC = () => {
  useEffect(() => {
    // Dynamic metadata synchronization adhering to React 18+ / React 19 StrictMode standards
    const setLink = (rel: string, href: string, type?: string, sizes?: string) => {
      let el = document.querySelector(`link[rel="${rel}"][href="${href}"]`) as HTMLLinkElement;
      if (!el) {
        el = document.createElement('link');
        el.rel = rel;
        el.href = href;
        if (type) el.type = type;
        if (sizes) el.sizes = sizes;
        document.head.appendChild(el);
      }
    };

    const setMeta = (attr: 'name' | 'property', key: string, content: string, media?: string) => {
      const selector = media ? `meta[${attr}="${key}"][media="${media}"]` : `meta[${attr}="${key}"]`;
      let el = document.querySelector(selector) as HTMLMetaElement;
      if (!el) {
        el = document.createElement('meta');
        el.setAttribute(attr, key);
        el.content = content;
        if (media) el.media = media;
        document.head.appendChild(el);
      } else {
        el.content = content;
      }
    };

    setLink('icon', '/favicon.svg', 'image/svg+xml', 'any');
    setLink('icon', '/favicon.ico', undefined, '32x32');
    setLink('apple-touch-icon', '/apple-touch-icon.png');
    setLink('manifest', '/site.webmanifest');
    setMeta('name', 'theme-color', '#ffffff');
    setMeta('name', 'theme-color', '#1a1a1a', '(prefers-color-scheme: dark)');
    setMeta('name', 'apple-mobile-web-app-title', 'AGNUS ');
    setMeta('property', 'og:image', 'https://github.com/rmccollage/AGNUS-GROUP-OF-COMPANY-assets/blob/main/logo.jpeg?raw=true');
  }, []);

  return null;
};
